version: '3.8'

services:

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build: ./api
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes: 
      - ./api/package.json/:/opt/api/package.json
      - ./api/package-lock.json:/opt/api/package-lock.json
      - ./api/src:/opt/api/src
    tty: true
    command: nodemon --watch ./src src/api-service.js
